### ISSUE TITLE
Bitmap images are allowed to have a final line missing with libgdiplus, not with GDI+

### ISSUE THREAD

**Issue by hughbe** [mono/libgdiplus#159]
In `test_invalidImageData` in `testbmpcodec.c`

```cpp
#if defined(USE_WINDOWS_GDIPLUS)
	BYTE noImageData[]            = {'B', 'M', 62, 0, 0, 0, 0, 0, 0, 0, 0x3E, 0, 0, 0, 40, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 255, 255, 255, 0};
#endif
	// FIXME: this should fail with OutOfMemory in libgdiplus.
#if defined(USE_WINDOWS_GDIPLUS)
	createFile (noImageData, OutOfMemory);
#endif
```

The fault is in
```
			if (size_read < size) {
				/* special case for missing data in the last line */
				if (line == result->active_bitmap->height - 1) {
					/* MS produce such files for storing ImageList bitmaps, see bug #80797 */
					int missing_size = size - size_read;
					memset (data_read + size_read, 0, missing_size);
				} else {
					status = OutOfMemory;
					goto error;
				}
			}
```

@akoeplinger is there a compat concern? This would disallow images that we previously allowed, but also increase compatability with GDI+...

It seems that the bug https://bugzilla.xamarin.com/show_bug.cgi?id=80797 doesn't exist as well? Maybe this is an old relic

**Comment by akoeplinger** [comment]
> @akoeplinger is there a compat concern? This would disallow images that we previously allowed, but also increase compatability with GDI+...

hmm, good question, according to the comment it seems to be used in System.Drawing

> It seems that the bug https://bugzilla.xamarin.com/show_bug.cgi?id=80797 doesn't exist as well? > Maybe this is an old relic

Yeah, those high bug numbers indicate old bugs from the Novell era, but https://bugzilla.novell.com/show_bug.cgi?id=80797 seems to be a private bug ...

**Comment by akoeplinger** [comment]
There's a little bit more context in the commit message: https://github.com/mono/libgdiplus/commit/579a8f59e854d91637d7c97fa3cd165b47ab5dc6

**Comment by filipnavara** [comment]
I believe the old issue mentioned in the code was cause by misunderstanding of the various bitmap header variations. The problematic case was probably 16-bit bitmap in 5-6-5 RGB format with BITMAPINFOHEADER. I believe a proper fix is missing these small changes:
- `gdip_read_BITMAPINFOHEADER` should fill in bV5RedMask & other masks with proper values.
- `gdip_read_bmp_image` no longer needs the hack marked with `/* MS produce such files (i.e. missing masks) for storing ImageList bitmaps, see bug #80797 */`
Additionally `gdip_get_bmp_pixelformat` seems to reject the combination of BI_BITFIELDS and bitCount == 32, which I believe is valid, so maybe we should investigate that and open an issue if necessary.

**Comment by hughbe** [comment]
Yeah, I agree that this is actually a bug in libgdiplus. I think the underlying problem has already been fixed:

> gdip_read_BITMAPINFOHEADER should fill in bV5RedMask & other masks with proper values.

This was fixed in https://github.com/mono/libgdiplus/pull/186

> gdip_read_bmp_image should no longer needs the hack marked with /* MS produce such files (i.e. missing masks) for storing ImageList bitmaps, see bug #80797 */ then

I've updated https://github.com/mono/libgdiplus/pull/259

> Additionally gdip_get_bmp_pixelformat seems to reject the combination of BI_BITFIELDS and bitCount == 32, which I believe is valid, so maybe we should investigate that and open an issue if necessary.

Correct! There's an issue for this: https://github.com/mono/libgdiplus/issues/158

**Comment by filipnavara** [comment]
I dont think PR #186 solved everything, it bails out here without filling in the default masks: https://github.com/mono/libgdiplus/blob/b19f4d6cf456dd935743c35eb5a61cdd2223f7a1/src/bmpcodec.c#L788
