### ISSUE TITLE
Update libgdiplus in Mono repositories, Linux Distributions & Homebrew

### ISSUE THREAD

**Issue by qmfrederik** [mono/libgdiplus#202]
With all the work @hughbe is doing it sure looks like libgdiplus is living its renaissance 😄 .

We rely on libgdiplus in our product and we try to make sure our users can install libgdiplus using the normal package management solutions on their platform (Linux distros + Homebrew).

Right now we build the packages ourselves but it would make sense to update the 'official' repositories.

Some thoughts:
- Mono already has Ubuntu, Debian and CentOS repositories which contain libgdiplus. The latest version of libgdiplus in there is 4.2 which dates from Dec. 2015. Is there an easy way to get more recent version of libgdiplus packaged in the Mono repositories?
- Is there any set process to get the Linux distro's to update libgdiplus? I think @akoeplinger mentioned most maintainers are members of the Xamarin team so perhaps this is an easy step 😄 .
- Homebrew seems to track the tags in the git repo, so that seems to be under control.

**Comment by qmfrederik** [comment]
For those on Ubuntu, I've added the libgdiplus package to our PPA:
https://launchpad.net/~quamotion/+archive/ubuntu/

We also have a repository with CentOS builds of libgdiplus although it's a bit outdated:
https://build.opensuse.org/package/show/home:qmfrederik/libgdiplus

If you want to create your own PPA with libgdiplus, here are the steps you can follow:

1. Get the build dependencies and the source for the current version of libgdiplus in Ubuntu
    ```
    apt-get build-dep libgdiplus
    apt-get source libgdiplus
    ```
2. Update the libgdiplus sources with the latest sources from master:
    ```
    wget https://github.com/mono/libgdiplus/archive/master.tar.gz -O libgdiplus-5.6.tar.gz
    cd libgdiplus-4.2
    uupdate ../libgdiplus-5.6.tar.gz
    cd ../libgdiplus-5.6
    rm -rf debian/patches/*
    ```
3. Create release notes. Make sure to target xenial and provide a valid e-mail address
    ```
    dch
    ```
4. Build a signed source package.
   ```
   debuild -S --force-sign -kXXYYZZ00
   ```
   Where `XXYYZZ00` is your gpg key id. If you're on Ubuntu, make sure your key is present in the `/usr/bin/gpg2 -K` output, there are two versions of gpg!
5. Push the package to your PPA
   ```
   cd ..
   dput ppa:[your_ppa]/ppa libgdiplus_5.6-0ubuntu1_source.changes
   ```

**Comment by filipnavara** [comment]
The current plan is to bump version number along with Mono 2018-08 branch. I know it's way overdue, but better late than never.

**Comment by qmfrederik** [comment]
Cool! Would that mean the packages at https://download.mono-project.com/repo/ubuntu/pool/main/libg/libgdiplus/ will also be updated?

**Comment by filipnavara** [comment]
I assume that they would, but I am not the one doing the packaging :)

**Comment by rdcm** [comment]
@filipnavara do you know about planned release date?
for some reasons build from sources unsuitable solution for my project

**Comment by filipnavara** [comment]
Mono has been branched for 2018-08 already, so maybe it's the time.

Unfortunately there are currently some issues preventing builds. The bzip.org domain name expired yesterday and the Windows packages use `vcpkg` which tried to download the bzip library from there. Similarly, macOS builds are broken because of botched `HarfBuzz` package updates, which needs to be propagated to Homebrew. Both of these issues are being worked on and should be fixed shortly (estimate: tomorrow).

@directhex @marek-safar Can we bump the libgdiplus version? I'd prefer to wait till Monday until we are sure the build dependency issues are sorted out though...

**Comment by rdcm** [comment]
Will the ubuntu/debian repositories be updated?

**Comment by directhex** [comment]
I'm a bit swamped this week, but I'll try to get on this.

**Comment by ras0219-msft** [comment]
@filipnavara The vcpkg bzip issues should be resolved :)

**Comment by filipnavara** [comment]
@ras0219-msft Thanks for notice! I saw it was fixed in your Git, but it took me a little while to figure out why the fix was not picked up automatically on the CI machines. Apparently we checkout old version of vcpkg due to https://github.com/Microsoft/vcpkg/issues/3631. I modified the script to cherry-pick the bzip2 commit, but it is only a temporary solution.

**Comment by directhex** [comment]
OK, so, looking at this issue.

I already updated libgdiplus on Linux to 5.6 a while back, and it shipped in 5.10+

Is there a _new_ new release to ship? Or, given the date on the bug, is that new enough?

**Comment by qmfrederik** [comment]
So, 5.6 is about a year old, and there have been ~300 commits since, fixing quite a lot of (compat) bugs.

So I'd say there's a new new version worth shipping :).

**Comment by qmfrederik** [comment]
@directhex I see you've bumped the version number in 70711a3c55b90238a311dc4d9da5838236d2581e. Any chance we can get a 5.23 tag, too? This would help get the package updated in Homebrew.

**Comment by directhex** [comment]
We'll need it bumped in the Mac versions first. I'm sure I did a PR to bump it... https://github.com/mono/mono/blob/master/packaging/MacSDK/libgdiplus.py is old though

**Comment by directhex** [comment]
https://github.com/mono/mono/pull/12339

**Comment by YaLTeR** [comment]
Could version 5.8 be tagged please?

**Comment by directhex** [comment]
There's some background stuff @akoeplinger is working on, which is why I haven't tagged/shipped stuff right now

**Comment by akoeplinger** [comment]
Given we have tagged and released recent version of libgdiplus to the Mono repositories I'm closing this issue :)

**Comment by qmfrederik** [comment]
Well, Debian/Ubuntu are still on version 4.2 of libgdiplus. It would be good if someone can bump the Debian version of libgdiplus.

And it turns out @directhex is listed as a maintainer at https://packages.debian.org/buster/libgdiplus 😄 . (If there's a more structured way for me to propose a libgdiplus update to Debian, let me know).

**Comment by directhex** [comment]
Are the daily bugfix releases over? :sweat_smile:

**Comment by filipnavara** [comment]
Yes, for today. ;-)

**Comment by qmfrederik** [comment]
@directhex Well, Debian has version 4.2, which is 4 years old. It would be great if at least Ubuntu 20.04 LTS has a more recent version of libgdiplus :smiley:
