### ISSUE TITLE
x64 Windows: access violation in FcInit()

### ISSUE THREAD

**Issue by hughbe** [mono/libgdiplus#204]
Exception thrown at 0x00007FF8AF470B1D (ntdll.dll) in libgdiplus.tests.exe: 0xC0000005: Access violation writing location 0xFFFFFFFFF6D1C290.

>	fontconfig.dll!readdir(DIR * dir) Line 100	C	Symbols loaded.
 	fontconfig.dll!FcDirScanConfig(_FcFontSet * set, _FcStrSet * dirs, _FcBlanks * blanks, const unsigned char * dir, int force, _FcConfig * config) Line 186	C	Symbols loaded.
 	fontconfig.dll!FcDirCacheScan(const unsigned char * dir, _FcConfig * config) Line 270	C	Symbols loaded.
 	fontconfig.dll!FcDirCacheRead(const unsigned char * dir, int force, _FcConfig * config) Line 319	C	Symbols loaded.
 	fontconfig.dll!FcConfigAddDirList(_FcConfig * config, _FcSetName set, _FcStrSet * dirSet) Line 355	C	Symbols loaded.
 	fontconfig.dll!FcConfigBuildFonts(_FcConfig * config) Line 388	C	Symbols loaded.
 	[Inline Frame] fontconfig.dll!FcInitLoadConfigAndFonts() Line 106	C	Symbols loaded.
 	fontconfig.dll!FcInit() Line 124	C	Symbols loaded.
 	libgdiplus.dll!GdiplusStartup(unsigned __int64 * token, const GdiplusStartupInput * input, GdiplusStartupOutput * output) Line 51	C	Symbols loaded.

Problematic code:

```cpp
        if(!dir->result.d_name || _findnext(dir->handle, &dir->info) != -1)
        {
            result         = &dir->result;
            result->d_name = dir->info.name;
        }
```

**Comment by hughbe** [comment]
Probably actually a bug in hexchat/gtk-win32

**Comment by qmfrederik** [comment]
@hughbe FYI: I added support for Visual Studio because that enabled me to debug a couple of PNG-related issues in libgdiplus. Using hexchat/gtk-win32 was a tactical choice as they provided the correct dependencies at the time.

There have been some changes in VC++ -land since, for example via the introduction of [vcpkg](https://github.com/Microsoft/vcpkg/). It looks like vcpkg now includes most, if not all, dependencies of libgdiplus.

It may be a better way to build & debug libgdiplus on Windows using Visual Studio.

**Comment by hughbe** [comment]
Awesome. I might investigate that, although I quite like the nuget restore approach.
The reason I’m focusing on a bunch of Windows stuff right now is because my Mac broke and I’m stuck on windows and want to run tests against libgdiplus

**Comment by qmfrederik** [comment]
The NuGet packages for VC++ are CoApp packages, and as far as I know CoApp is no longer under active maintenance.
I liked the idea too, but it looks like vcpkg is the way forward.

**Comment by hughbe** [comment]
Fixed when we updated our GTK version on Windows
