### ISSUE TITLE
GdipGetPathData memory managment

### ISSUE THREAD

**Issue by filipnavara** [mono/libgdiplus#223]
It seems that the implementation of GdipGetPathData is pretty wrong in relation to how it manages memory. The caller is supposed to allocate the buffers and specify the point count. The current implementation leaks memory on each call by allocating buffers and overriding the passed buffers.

Reference: https://referencesource.microsoft.com/#System.Drawing/commonui/System/Drawing/Advanced/GraphicsPath.cs,321

**Comment by hughbe** [comment]
Should be closed, fixed by #227a
