### ISSUE TITLE
Start supporting pango?

### ISSUE THREAD

**Issue by Artoria2e5** [mono/libgdiplus#364]
libgdiplus does not consider font fallbacks for text rendering, often breaking multilingual display ([bz#39418](https://bugzilla.xamarin.com/show_bug.cgi?id=39418)). According to the cairo folks, to handle fallbacks without using pango, [you must do it yourself with fontconfig](https://lists.freedesktop.org/archives/cairo/2015-May/026282.html). Mixed scripts are really not *that* rare in current usage, and using pango *does* solve the fallback issue. Please consider making the pango support a bit more supported, even default.

**Comment by filipnavara** [comment]
FontConfig is used even in the builds without Pango. However, rendering text in non-Latin alphabets  or with any more complex text layout is not. There's an ongoing debate about this issue at https://github.com/mono/libgdiplus/pull/269.

**Comment by filipnavara** [comment]
Pango support is official now, can be closed now.
