### ISSUE TITLE
GdipDrawCurve2 with a large tension differs from GDI+

### ISSUE THREAD

**Issue by hughbe** [mono/libgdiplus#423]
### Code
```cpp
static void createImageGraphics (INT width, INT height, GpImage **image, GpGraphics **graphics)
{
	GpStatus status;

	status = GdipCreateBitmapFromScan0 (width, height, 0, PixelFormat32bppARGB, NULL, (GpBitmap **) image);
	assertEqualInt (status, Ok);

	status = GdipGetImageGraphicsContext (*image, graphics);
	assertEqualInt (status, Ok);
}

static void test_drawCurve2 ()
{
	GpStatus status;
	GpImage *image;
	GpGraphics *graphics;
	GpPen *pen;

	GdipCreatePen1 (0xFF00FF00, 1, UnitPixel, &pen);
	
	GpPointF normal7[] = {
		{10, 20},
		{60, 30},
		{60, 50},
		{80, 70},
		{100, 90},
		{150, 110},
		{200, 130},
	};

	// Small (3) - large tension.
	createImageGraphics (256, 256, &image, &graphics);
	status = GdipDrawCurve2 (graphics, pen, normal7, 3, 10);
	assertEqualInt (status, Ok);

	dumpImage (image);

	GdipDeleteGraphics (graphics);
	GdipDisposeImage (image);

	GdipDeleteGraphics (graphics);
	GdipDisposeImage (image);
}
```

(Ignoring the black background.)

#### GDI+
![image](https://user-images.githubusercontent.com/1275900/44751858-29ddde00-ab11-11e8-9f5d-94987eefb97e.png)

### Libgdiplus
![test-image](https://user-images.githubusercontent.com/1275900/44751872-36623680-ab11-11e8-9fd2-8a8c9f1610a7.png)

**Comment by hughbe** [comment]
This could be a generic issue with 3 points in a curve - the results differ for all tensions

**Comment by PreferLinux** [comment]
In GdipDrawCurve2, it calculates the number of segments with `int segments = (count > 3) ? (count - 1) : (count - 2);` (graphics.c line 1176). With a count of 3, this gives only 1 segment. This means that make_curve (graphics-cairo.c line 286) gets a length of 1 and only draws one curve, in this case starting at (10, 20) and ending at (60, 30). So I'm guessing that's the problem.

**Comment by hughbe** [comment]
Fix in https://github.com/mono/libgdiplus/pull/424
