### ISSUE TITLE
Sources tarball is missing graphic files required for tests

### ISSUE THREAD

**Issue by kapsh** [mono/libgdiplus#531]
Source tarball https://download.mono-project.com/sources/libgdiplus/libgdiplus-5.6.tar.gz is missing any graphic files in `tests` directory, they are present only in archives from page https://github.com/mono/libgdiplus/releases

This causes `testgraphics` and `testpng` to fail for ones who want to build libgdiplus from sources and test this build.

**Comment by akoeplinger** [comment]
Fixed by c6708c5fdf919ffc267e921e207de95c2b9a0e63, thank you! It'll be in the upcoming 5.8 release.

**Comment by kapsh** [comment]
Nice, thanks.
