### ISSUE TITLE
Text anti-aliasing not set

### ISSUE THREAD

**Issue by JeremyKuhne** [mono/libgdiplus#535]
When rendering text it is always coming out with sub-pixel rendering (e.g. ClearType like), at least when running on Raspbian. The `TextRenderingHint` isn't hooked up:

https://github.com/mono/libgdiplus/blob/c6708c5fdf919ffc267e921e207de95c2b9a0e63/src/text-cairo.c#L176-L200

(It also isn't hooked up in the Pango implementation)

This is creating some grief for me when trying to create bitmaps with text for IOT displays. When writing to a 3 color e-ink display anti-aliasing isn't helpful. :)

I presume that we want to map something like this:

| Cairo | System.Drawing / Gdi+ |
|-------|-------|
|  `CAIRO_ANTIALIAS_NONE` `CAIRO_HINT_METRICS_OFF` `CAIRO_HINT_STYLE_NONE` | `TextRenderingHint.SingleBitPerPixel` |
|  `CAIRO_ANTIALIAS_NONE` `CAIRO_HINT_METRICS_ON` `CAIRO_HINT_STYLE_MEDIUM` | `TextRenderingHint.SingleBitPerPixelGridFit` |
|  `CAIRO_ANTIALIAS_GRAY` `CAIRO_HINT_METRICS_OFF` `CAIRO_HINT_STYLE_NONE` | `TextRenderingHint.AntiAlias` |
|  `CAIRO_ANTIALIAS_GRAY` `CAIRO_HINT_METRICS_ON` `CAIRO_HINT_STYLE_MEDIUM` | `TextRenderingHint.AntiAliasGridFit` |
| `CAIRO_ANTIALIAS_SUBPIXEL` `CAIRO_HINT_METRICS_ON` `CAIRO_HINT_STYLE_MEDIUM` | `TextRenderingHint.ClearTypeGridFit` |

Here is a sample image from Windows (download and zoom in to see the sub-pixel color fringing):

![testantialiasing](https://user-images.githubusercontent.com/8184940/53219021-4d429b00-3613-11e9-941a-29b9fe312b6f.png)
The code I used to generate the image:

``` C#
Bitmap bitmap = new Bitmap(300, 200);

Font font = new Font(FontFamily.GenericMonospace, 8.0f);
using (Graphics g = Graphics.FromImage(bitmap))
{
    g.Clear(Color.White);
    g.DrawString("Test NotSet", font, Brushes.Black, 10.0f, 10.0f);
    g.TextRenderingHint = TextRenderingHint.AntiAlias;
    g.DrawString("Test AntiAlias", font, Brushes.Black, 10.0f, 30.0f);
    g.TextRenderingHint = TextRenderingHint.AntiAliasGridFit;
    g.DrawString("Test AntiAliasGridFit", font, Brushes.Black, 10.0f, 50.0f);
    g.TextRenderingHint = TextRenderingHint.ClearTypeGridFit;
    g.DrawString("Test ClearTypeGridFit", font, Brushes.Black, 10.0f, 70.0f);
    g.TextRenderingHint = TextRenderingHint.SingleBitPerPixel;
    g.DrawString("Test SingleBitPerPixel", font, Brushes.Black, 10.0f, 90.0f);
    g.TextRenderingHint = TextRenderingHint.SingleBitPerPixelGridFit;
    g.DrawString("Test SingleBitPerPixelGridFit", font, Brushes.Black, 10.0f, 110.0f);
    g.TextRenderingHint = TextRenderingHint.SystemDefault;
    g.DrawString("Test SystemDefault", font, Brushes.Black, 10.0f, 1300.0f);
}

bitmap.Save("textaliasing.png", ImageFormat.Png);
```

It seems like ClearType is the default when unspecified. I don't have samples from the Cairo end of things yet. Wanted to get this issue open so I can track it in IOT/CoreFX.

**Comment by safern** [comment]
cc: @filipnavara @marek-safar @hughbe might have some insights on how to fix this.

**Comment by safern** [comment]
cc @akoeplinger
