### ISSUE TITLE
For some images HorizontalResolution and VerticalResolution erroneusly returns 0

### ISSUE THREAD

**Issue by tikal** [mono/libgdiplus#539]
Porting over https://bugzilla.xamarin.com/show_bug.cgi?id=33310

I just reproduced this for some images on my local using version 5.6

**Comment by qmfrederik** [comment]
@tikal I have a fix ready for this as part of #596, but I'm lacking a simple unit test.

Do you happen to have a small JPEG image which can be used to reproduce this issue?

**Comment by tikal** [comment]
Unfortunately not, I just remember it was an image that only Chrome was able to render w/o problems
