### ISSUE TITLE
Cannot install RPM ... nothing provides libtiff.so.5(LIBTIFF_4.0)

### ISSUE THREAD

**Issue by markphip** [mono/libgdiplus#742]
Realize this is probably a package manager problem (Mariner-CBL 2.0), looking for tips and what to ask them to fix. I have libtiff-devel 4.4.0 installed and it seemingly has the right libraries installed:

```bash
$ sudo tdnf repoquery -q -l libtiff | grep libtiff
/usr/lib/libtiff.so.5
/usr/lib/libtiff.so.5.7.0
/usr/lib/libtiff.so.5.8.0
/usr/lib/libtiffxx.so.5
/usr/lib/libtiffxx.so.5.7.0
/usr/lib/libtiffxx.so.5.8.0
```

When I try to install mono, it fails:

```bash
$ sudo tdnf install mono-core
Loaded plugin: tdnfrepogpgcheck
1. nothing provides libtiff.so.5(LIBTIFF_4.0)(64bit) needed by libgdiplus0-5.6-0.xamarin.2.epel8.x86_64
Found 1 problem(s) while resolving
Error(1301) : Solv general runtime error
```

I tried comparing the spec for Mariner with CentOS and Fedora and nothing jumps out. I am just assuming install works on CentOS/Fedora but I do not see where their libtiff spec is significantly different from Mariner.

**Comment by akoeplinger** [comment]
We solved this offline. You can download https://download.mono-project.com/repo/centos8-stable/m/mono-core/mono-core-6.12.0.107-0.xamarin.9.epel8.x86_64.rpm and extract it manually as a workaround.

Note: this is just to get you unblocked, it is not recommended for production.
